version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ternakuy-app
    container_name: ternakuy-app
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file:
      - .env
